travis: fix stdlib in linux/trusty/clang configuration
In default configuration clang-5 uses stdlib from gcc-4.8.

Full error log from Clang 5.0.0:
json.hpp:16188:38: error: too few template
      arguments for class template 'less'
    using object_comparator_t = std::less<>;
                                     ^
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_function.h:231:12: note:
      template is declared here
    struct less : public binary_function<_Tp, _Tp, bool>